### ISSUE TITLE
画像が表示されない

### ISSUE THREAD

**Issue by shikato** [shikato/pixiv_sk#16]

**Comment by Ocrosoft** [comment]
Unfortunately, pixiv has been updated...
Use [this script](https://greasyfork.org/zh-CN/scripts/30766) and wait for shikato to update his script...

**Comment by shikato** [comment]
I update pixiv_sk. 
https://github.com/shikato/pixiv_sk/pull/17

**Comment by Ocrosoft** [comment]
Great! I'll try it later.
